devops/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),
    path('mdeditor/', include('mdeditor.urls')),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.urls import path
from . import views

app_name = 'web'
urlpatterns = [
    path('',views.Index,name='index'),
    path('markdowntest/',views.MarkDownTest,name='markdowntest'),
    path('articletest/',views.ArticleTest,name='articletest'),
    path('login',views.Login,name='login'),
    path('logincheck/',views.LoginCheck,name='logincheck'),
    path('sign', views.Sign, name='sign'),
    path('signcheck/', views.SignCheck, name='signcheck'),

    # banbenkongzhi
    path('svnindex/', views.SVNIndex, name='svnindex'),
    # blogsystem
    path('djangoblogindex/', views.DjangoBlogIndex, name='djangoblogindex'),
    path('djangoblogshow/', views.DjangoBlogShow, name='djangoblogshow'),
]

web/models.py
#encoding=utf-8
from django.db import models
from django.utils import timezone
import datetime
from mdeditor.fields import MDTextField

# Create your models here.
# 系统用户表
class AccountInformation(models.Model):
    username = models.CharField(max_length=20)
    password = models.CharField(max_length=20)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.username
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


# 文章信息表
class Article(models.Model):
    title = models.CharField(max_length=20)
    author = models.CharField(max_length=20)
    tags = models.CharField(max_length=30)
    introduction = models.CharField(max_length=180)
    images = models.CharField(max_length=360)
    pub_date = models.DateTimeField('date published')
    content = MDTextField()
    def __str__(self):
        return self.title
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

web/views.py
from django.shortcuts import render
from .models import AccountInformation, Article
from django.utils import timezone
from markdown import markdown

#导入Paginator,EmptyPage和PageNotAnInteger模块
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# Create your views here.
def Index(request):
    return render(request, 'web/index.html')

def MarkDownTest(request):
    markdown_data = '''
# markdown测试
## 二级标签
### 三级标签
- 列表1
- 列表2
```python
#encoding=utf-8

def Login(request):
    error_data = "Login"
    return render(request, 'web/login.html',{"error_data":error_data})
```
'''
    markdown_data = markdown(markdown_data.replace("\r\n", '  \n'),extensions=[
                                      'markdown.extensions.extra',
                                      'markdown.extensions.codehilite',
                                      'markdown.extensions.toc',
                                  ],safe_mode=True,enable_attributes=False)
    return render(request, 'web/markdowntest.html', {'markdown_data': markdown_data})


def ArticleTest(request):
    article_data = Article.objects.get(title='导读：知其然知其所以然')
    article_content_data = markdown(article_data.content)
    return render(request, 'web/articletest.html', {'article_content_data': article_content_data,'article_data':article_data})

def Login(request):
    error_data = "Login"
    return render(request, 'web/login.html',{"error_data":error_data})

def LoginCheck(request):
    username = request.GET['username']
    password = request.GET['password']
    if len(AccountInformation.objects.filter(username=username)) > 0:
        username_password_check = AccountInformation.objects.get(username=username)
        username_check =  username_password_check.username
        password_check = username_password_check.password
        if username_check == username and password_check == password:
            return render(request, 'web/index.html')
        else:
            error_data = "密码信息错误有误，请重新登陆！"
            return render(request, 'web/login.html',{"error_data":error_data})
    else:
        error_data = "该账号不存在，请联系管理员注册！"
        return render(request, 'web/login.html',{"error_data":error_data})

def Sign(request):
    error_data = "Sign in"
    return render(request, 'web/sign.html',{"error_data":error_data})

def SignCheck(request):
    username = request.GET['username']
    password = request.GET['password']
    password_again = request.GET['password_again']
    if len(AccountInformation.objects.filter(username=username)) == 0 and password == password_again :
        new_user = AccountInformation(username=username, password=password,pub_date=timezone.now())
        new_user.save()
        error_data = "Login"
        return render(request,  'web/login.html',{"error_data":error_data})
    else:
        error_data = "用户名已注册或两次输入的密码不一致"
        return render(request, 'web/sign.html',{'error_data':error_data})



def SVNIndex(request):
    return render(request, 'web/banbenkongzhi/svnindex.html')

def DjangoBlogIndex(request):
    articledata = Article.objects.all()



    # 生成paginator对象,定义每页显示条记录
    paginator = Paginator(articledata, 4)  # Show 25 contacts per page
    # 从前端获取当前的页码数
    page = request.GET.get('page',1)
    try:
        # 获取当前页码的记录
        contacts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        # 如果用户输入的页码不是整数时,显示第1页的内容
        contacts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        # 如果用户输入的页数不在系统的页码列表中时,显示最后一页的内容
        contacts = paginator.page(paginator.num_pages)
    # 把当前的页码数转换成整数类型
    currentPage = int(page)
    return render(request, 'web/blogsystem/index.html',{'contacts':contacts,'paginator':paginator,'currentPage':currentPage})

def DjangoBlogShow(request):
    id = request.GET['id']
    articledata = Article.objects.get(id=id)
    article_content_data = markdown(articledata.content)
    return render(request, 'web/blogsystem/show.html',{'articledata':articledata,'article_content_data':article_content_data})

web/templates/web/articletest.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>{{ article_data.title }}</title>
</head>
<body>

<link rel="stylesheet" type="text/css" href="{% static 'web/css/code.css' %}">
{{ article_content_data|safe }}
</body>
</html>

web/templates/web/banbenkongzhi/gitlabindex.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

web/templates/web/banbenkongzhi/svnindex.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>SVN</title>
	<link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
	<script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% load static %}
</head>
<body>
{% include "web/nav.html" %}

<div class="center-block">
    <div class="row" style="margin-bottom: 80px;margin-top: 80px">
        <div class="col-sm-6 col-md-4 col-md-offset-2">
            <a href="http://172.16.1.253/svn/root/Product/BH-D408/trunk" target="_blank" class="thumbnail">
                <img src="{% static 'web/images/bg2.jpg' %}">
                <div class="carousel-caption">
                <h1>BH-D408/trunk</h1>
                <p>Ceph/云盘 部署</p>
                </div>
            </a>
        </div>
        <div class="col-sm-6 col-md-4">
            <a href="http://172.16.1.253/svn/root/Product/BH-D408/branches" target="_blank" class="thumbnail">
                <img src="{% static 'web/images/bg2.jpg' %}">
                <div class="carousel-caption">
                <h1>BH-D408/branches</h1>
                <p>OpenStack 云平台部署</p>
                </div>
            </a>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6 col-md-4 col-md-offset-2">
            <a href="#" class="thumbnail">
                <img src="{% static 'web/images/bg2.jpg' %}">
                <div class="carousel-caption">
                <h1>BH-D40X/beta</h1>
                <p>归一平台 部署/更新/自动化测试</p>
                </div>
            </a>
        </div>
    </div>
</div>


</body>
</html>

web/templates/web/blogsystem/about.html
{% load static %}
{% for data in contacts %}
    <!-- about -->
	<div class="about">
		<div class="container">
			<div class="agileits_about_grids">
                <a href="/djangoblogshow/?id={{ data.id }}">
				<div class="col-md-6 agileits_about_grid_left">
					<h3>{{ data.title }}</h3>
					<p>{{ data.introduction }}</p>
				</div>
				<div class="col-md-6 agileits_about_grid_right">
					<img src="{{ data.images }}" alt=" " class="img-responsive" />
				</div>
				<div class="clearfix"> </div>
                </a>
			</div>
		</div>
	</div>
	<!-- //about -->
{% empty %}
    <p>暂无数据。</p>
{% endfor %}

web/templates/web/blogsystem/hot.html
{% load static %}

	<div class="gallery" id="gallery">
		<h3>热门文章</h3>
		<p class="nostrud agileits-w3layouts">近期读者最喜爱的博文</p>
		<div class="w3agile_gallery_grids">
            {% for data in contacts %}
			<div class="col-md-3 w3agile_gallery_grid">
				<div class="w3agile_gallery_image">
					<a class="sb" href="{{ data.images }}" title="{{ data.title }}" titleid="{{ data }}">
						<figure>
							<img src="{{ data.images }}" alt="" class="img-responsive" />
							<figcaption>
								<h4>{{ data.title }}</h4>
								<p>
									{{ data.introduction }}
								</p>
							</figcaption>
						</figure>
					</a>
				</div>
			</div>
            {% empty %}
                <p>暂无数据。</p>
            {% endfor %}
		   <div class="clearfix"> </div>
		</div>
		<script type="text/javascript" src="{%  static 'web/blogsystem/js/smoothbox.jquery2.js' %}"></script>
	</div>




{#    <!-- //team-bottom -->#}
{#	<!-- gallery -->#}
{#	<div class="gallery" id="gallery">#}
{#		<h3>热门文章</h3>#}
{#		<p class="nostrud agileits-w3layouts">近期读者最喜爱的博文</p>#}
{#		<div class="w3agile_gallery_grids">#}
{#			<div class="col-md-3 w3agile_gallery_grid">#}
{#				<div class="w3agile_gallery_image">#}
{#					<a class="sb" href="{%  static 'web/blogsystem/images/8.jpg' %}" title="导读：知其然知其所以然">#}
{#						<figure>#}
{#							<img src="{%  static 'web/blogsystem/images/8.jpg' %}" alt="" class="img-responsive" />#}
{#							<figcaption>#}
{#								<h4>导读：知其然知其所以然</h4>#}
{#								<p>#}
{#									Openstack学习必然是一个艰难的事情，但是真正理解了各个OpenStack组件的功能以及组件间的相互协作流程，那么在日常工作中将会是一笔无形的财富。未来遇见了再多bug时，也不会慌，因为你知道每个组件负责什么工作，也知道每个组件是怎样去工作，排查思路了然于心。#}
{#								</p>#}
{#							</figcaption>#}
{#						</figure>#}
{#					</a>#}
{#				</div>#}
{#			</div>#}
{#			<div class="col-md-3 w3agile_gallery_grid">#}
{#				<div class="w3agile_gallery_image">#}
{#					<a class="sb" title="何为身份认证服务 Keystone" href="{%  static 'web/blogsystem/images/9.jpg' %}">#}
{#						<figure>#}
{#							<img src="{%  static 'web/blogsystem/images/9.jpg' %}" alt="" class="img-responsive" />#}
{#							<figcaption>#}
{#								<h4>何为身份认证服务 Keystone</h4>#}
{#								<p>#}
{#									OpenStack Identity服务因为其特殊的特性，必然是我们在学习OpenStack中第一个接触的服务。我们每个人都是一个用户个体，当我们使用OpenStack任何一个服务时，都需要我们出示OpenStack Identity服务给我们颁发的通行证书，待这些服务验证过通行证书之后才开放相应的功能给我们使用。#}
{#								</p>#}
{#							</figcaption>#}
{#						</figure>#}
{#					</a>#}
{#				</div>#}
{#			</div>#}
{#			<div class="col-md-3 w3agile_gallery_grid">#}
{#				<div class="w3agile_gallery_image">#}
{#					<a class="sb" title="何为身份认证服务 Glance" href="{%  static 'web/blogsystem/images/10.jpg' %}">#}
{#						<figure>#}
{#							<img src="{%  static 'web/blogsystem/images/10.jpg' %}" alt="" class="img-responsive" />#}
{#							<figcaption>#}
{#								<h4>何为身份认证服务 Glance</h4>#}
{#								<p>#}
{#									我们常说的Glance 便是OpenStack Image服务的组件。镜像服务顾名思义是指管理镜像的服务啊！管理镜像实际上就是对镜像的发现、注册、检索、删除。同样Glance 也提供了一个 REST API，我们可以通过API查询虚拟机镜像的元数据并检索出实际镜像。通过Image服务管理虚拟机镜像存储到指定位置，这个位置可以是最简单的文件系统还可以是Open#}
{#								</p>#}
{#							</figcaption>#}
{#						</figure>#}
{#					</a>#}
{#				</div>#}
{#			</div>#}
{#			<div class="col-md-3 w3agile_gallery_grid w3-agileits">#}
{#				<div class="w3agile_gallery_image">#}
{#					<a class="sb" title="深入理解keystone九大概念" href="{%  static 'web/blogsystem/images/11.jpg' %}">#}
{#						<figure>#}
{#							<img src="{%  static 'web/blogsystem/images/11.jpg' %}" alt="" class="img-responsive" />#}
{#							<figcaption>#}
{#								<h4>深入理解keystone九大概念</h4>#}
{#								<p>#}
{#									学习一个OpenStack组件，首先我们要了解它的构成，然后一步步的去剖析这些细小的部分的功能，最后将整个组件的工作流程梳理出来。接下来，请跟着我的节奏，去了解一下keystone组件的九大概念。#}
{#								</p>#}
{#							</figcaption>#}
{#						</figure>#}
{#					</a>#}
{#				</div>#}
{#			</div>#}
{#		   <div class="clearfix"> </div>#}
{#		</div>#}
{#		<script type="text/javascript" src="{%  static 'web/blogsystem/js/smoothbox.jquery2.js' %}"></script>#}
{#	</div>#}
{#	<!-- //gallery -->#}

web/templates/web/blogsystem/index.html
<!DOCTYPE html>
<html lang="en">
<head>
{% load static %}
<title>Home</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- Custom Theme files -->
<link href="{%  static 'web/blogsystem/css/bootstrap.css' %}" rel='stylesheet' type='text/css' />
<link href="{%  static 'web/blogsystem/css/style.css' %}" rel='stylesheet' type='text/css' />
<link rel="stylesheet" href="{%  static 'web/blogsystem/css/smoothbox.css' %}" type='text/css' >
<!-- //Custom Theme files -->
<!-- js -->
<script src="{%  static 'web/blogsystem/js/jquery.min.js' %}"></script>
<link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
<!-- //js -->
<!-- web font -->
<link href="http://fonts.googleapis.com/css?family=Work+Sans:100,200,300,400,500,600,700,800,900" rel="stylesheet">
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
<!-- //web font -->

</head>
<body>
{# 主导航栏 #}
{% include "web/nav.html" %}
{# 博客导航栏 #}
{% include "web/blogsystem/nav.html" %}
{# 博客文章栏 #}
{% include "web/blogsystem/about.html" %}


{# 翻页代码 #}
<div class="container">
    <ul class="pagination">
        {#上一页按钮开始#}
        {# 如果当前页有上一页#}
        {% if contacts.has_previous %}
            {#  当前页的上一页按钮正常使用#}
            <li class="previous"><a href="/djangoblogindex/?page={{ contacts.previous_page_number }}">上一页</a></li>
        {% else %}
            {# 当前页的不存在上一页时,上一页的按钮不可用#}
            <li class="previous disabled"><a href="#">上一页</a></li>
        {% endif %}
        {#上一页按钮结束#}
        {# 页码开始#}
        {% for num in paginator.page_range  %}
            {% if num == currentPage %}
                <li  class="item active"><a href="/djangoblogindex/?page={{ num }}">{{ num }}</a></li>
            {% else %}
                <li  class="item"><a href="/djangoblogindex/?page={{ num }}">{{ num }}</a></li>
            {% endif %}
        {% endfor %}
        {#页码结束#}
        {# 下一页按钮开始#}
        {% if contacts.has_next %}
            <li class="next"><a href="/djangoblogindex/?page={{ contacts.next_page_number }}">下一页</a></li>
        {% else %}
            <li class="next disabled"><a href="#">下一页</a></li>
        {% endif %}
        {# 下一页按钮结束#}
    </ul>
</div>

{# hot 文章 #}
{% include "web/blogsystem/hot.html" %}

</body>
</html>

web/templates/web/blogsystem/markdown.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'web/css/code.css' %}">
<a href="/djangoblogindex/"><button class="btn btn-primary " data-toggle="modal" data-target="#myModal" style="margin-left: 40px">< < 返回首页</button></a>
<!-- about -->
<div class="about">
    <div class="container">
        <div class="agileits_about_grids">

            <div class="col-md-12 ">
                <h1>{{ articledata.title }}</h1>
                <br>
                {{ article_content_data|safe }}
            </div>


        </div>
    </div>
</div>
<!-- //about -->

web/templates/web/blogsystem/show.html
<!DOCTYPE html>
<html lang="en">
<head>
{% load static %}
<title>{{ articledata.title }}</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- Custom Theme files -->
<link href="{%  static 'web/blogsystem/css/bootstrap.css' %}" rel='stylesheet' type='text/css' />
<link href="{%  static 'web/blogsystem/css/style.css' %}" rel='stylesheet' type='text/css' />
<link rel="stylesheet" href="{%  static 'web/blogsystem/css/smoothbox.css' %}" type='text/css' >
<!-- //Custom Theme files -->
<!-- js -->
<script src="{%  static 'web/blogsystem/js/jquery.min.js' %}"></script>
<link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
<!-- //js -->
<!-- web font -->
<link href="http://fonts.googleapis.com/css?family=Work+Sans:100,200,300,400,500,600,700,800,900" rel="stylesheet">
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
<!-- //web font -->

</head>
<body>
{# 主导航栏 #}
{% include "web/nav.html" %}
{# 博客导航栏 #}
{#{% include "web/blogsystem/nav.html" %}#}
{# 博客文章栏 #}
{% include "web/blogsystem/markdown.html" %}
</body>
</html>

web/templates/web/index.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<title>DevOps System</title>
	<link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
	<script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>

    {% load static %}
</head>
<body>
{# 导航栏 #}
{% include "web/nav.html" %}

{# 轮播图 #}
{% include "web/carousel.html" %}





</body>
</html>

web/templates/web/login.html
<!DOCTYPE html>
<html>	
<head>
<title>Login</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<meta name="keywords" content="Flat Dark Web Login Form Responsive Templates, Iphone Widget Template, Smartphone login forms,Login form, Widget Template, Responsive Templates, a Ipad 404 Templates, Flat Responsive Templates" />
{% load static %}
<link href="{% static 'web/css/style.css' %}" rel='stylesheet' type='text/css' />
<!--webfonts-->
<link href='http://fonts.useso.com/css?family=PT+Sans:400,700,400italic,700italic|Oswald:400,300,700' rel='stylesheet' type='text/css'>
<link href='http://fonts.useso.com/css?family=Exo+2' rel='stylesheet' type='text/css'>
<link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
<!--//webfonts-->
<script src="http://ajax.useso.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
</head>
<body>
<script>$(document).ready(function(c) {
	$('.close').on('click', function(c){
		$('.login-form').fadeOut('slow', function(c){
	  		$('.login-form').remove();
		});
	});	  
});
</script>
 <!--SIGN UP-->
<h1>DevOps 开发者平台</h1>
<div class="login-form">
{#	<div class="close"> </div>#}
		<div class="head-info">
            {{ error_data }}
{#			<label class="lbl-1"> </label>#}
{#			<label class="lbl-2"> </label>#}
{#			<label class="lbl-3"> </label>#}
		</div>
			<div class="clear"> </div>
	<div class="avtar">
		<img src="../../static/web/images/avtar.png" />
	</div>
			<form action="/logincheck/" method="get">
					<input type="text" class="text" name="username" value="Username" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Username';}" >
						<div class="key">
					<input type="password" value="Password" name="password" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Password';}">
						</div>
                        <br>
                        <br>
                        <button type="submit" class="btn btn-success btn-lg" name="submit" style="margin-left:30px;">登   录</button>
                        <a href="{% url 'web:sign'%}" class="btn btn-success btn-lg" name="sign" style="margin-left:30px;">注   册</a>
                        <br>
                        <br>
                        <br>
{#                        <input type="submit" class="btn btn-success pull-left" name="submit">#}

            </form>
</div>
 <div class="copy-rights">
     <p>Copyright &copy; 2018.Company name All rights reserved.Welcome to my <a href="http://www.cuijanmin.top/" target="_blank" title="my blog">blog.</a></p>
</div>
</body>
</html>

web/templates/web/markdown.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MarkDown</title>
</head>
<body>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'web/css/code.css' %}">


{{ markdown_data|safe }}



</body>
</html>

web/templates/web/markdowntest.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MarkDown</title>
</head>
<body>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'web/css/code.css' %}">
{{ markdown_data|safe }}
</body>
</html>

web/templates/web/sign.html
<!DOCTYPE html>
<html>
<head>
<title>Sign</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<meta name="keywords" content="Flat Dark Web Login Form Responsive Templates, Iphone Widget Template, Smartphone login forms,Login form, Widget Template, Responsive Templates, a Ipad 404 Templates, Flat Responsive Templates" />
{% load static %}
<link href="{% static 'web/css/style.css' %}" rel='stylesheet' type='text/css' />
<!--webfonts-->
<link href='http://fonts.useso.com/css?family=PT+Sans:400,700,400italic,700italic|Oswald:400,300,700' rel='stylesheet' type='text/css'>
<link href='http://fonts.useso.com/css?family=Exo+2' rel='stylesheet' type='text/css'>
<link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
<!--//webfonts-->
<script src="http://ajax.useso.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
</head>
<body>
<script>$(document).ready(function(c) {
	$('.close').on('click', function(c){
		$('.login-form').fadeOut('slow', function(c){
	  		$('.login-form').remove();
		});
	});
});
</script>
 <!--SIGN UP-->
<h1>DevOps 开发者平台</h1>
<div class="login-form">
{#	<div class="close"> </div>#}
		<div class="head-info">
            {{ error_data }}
{#			<label class="lbl-1"> </label>#}
{#			<label class="lbl-2"> </label>#}
{#			<label class="lbl-3"> </label>#}
		</div>
			<div class="clear"> </div>
	<div class="avtar">
		<img src="../../static/web/images/avtar.png" />
	</div>
			<form action="/signcheck/" method="get">
					<input type="text" class="text" name="username" value="Username" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Username';}">
					<input type="password_again" value="Password" name="password" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Password';}">
                    <div class="key">
					<input type="password_again" value="Password Again" name="password_again" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Password';}">
                    </div>
                    <br>
                    <br>
                    <button type="submit" class="btn btn-success btn-lg" name="sign" style="margin-left:30px;">注   册</button>
                    <a href="{% url 'web:login'%}" class="btn btn-success btn-lg" name="submit" style="margin-left:30px;">返   回</a>
                    <br>
                    <br>
                    <br>
{#                        <input type="submit" class="btn btn-success pull-left" name="submit">#}

            </form>
</div>
 <div class="copy-rights">
     <p>Copyright &copy; 2018.Company name All rights reserved.Welcome to my <a href="http://www.cuijanmin.top/" target="_blank" title="my blog">blog.</a></p>
</div>
</body>
</html>